name: 'ğŸš€ Release Build & Publish'

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout for CI ğŸ›ï¸'
        uses: actions/checkout@v4
      - name: 'Set up JDK 17 ğŸ“¦'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 'Set up JDK 21 ğŸ“¦'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: 'Set up Gradle âš™ï¸'
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.7'
      - name: 'Initialize Gradle Wrapper ğŸš€'
        run: gradle wrapper
      - name: 'Change Wrapper Permissions ğŸ”“'
        run: chmod +x ./gradlew
      - name: 'Build NMS Module ğŸ”¨'
        run: ./gradlew :nms:build
      - name: 'Build PlayerAnimator Module ğŸ­'
        run: ./gradlew :playeranimator:build
      - name: 'Build Main Project ğŸ—ï¸'
        run: ./gradlew build
      - name: 'Upload Build Artifact ğŸ“¦'
        uses: actions/upload-artifact@v4
        with:
          name: Gestures
          path: build/libs/Gestures v**.jar
      - name: 'Publish to repo.voxelarc.net ğŸ“¡'
        run: ./gradlew publish
        env:
          VOXELARC_REPO_USERNAME: ${{ secrets.VOXELARC_REPO_USERNAME }}
          VOXELARC_REPO_PASSWORD: ${{ secrets.VOXELARC_REPO_PASSWORD }}